# Generated by Django 4.0.4 on 2022-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_alter_attendance_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='today_date',
            field=models.DateTimeField(),
        ),
    ]
