# Generated by Django 4.0.4 on 2022-06-01 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0006_alter_attendance_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='today_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
